# Generated by Django 4.0.4 on 2022-05-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cropsagriculture',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructureairport',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructurebridge',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructurefuel',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructureport',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructureroads',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructuretelecommunication',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilityelectricity',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilitywater',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
