# Generated by Django 4.0.4 on 2022-05-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0002_alter_building_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructureairport',
            options={'verbose_name': 'Infrastructure Aerial', 'verbose_name_plural': 'Infrastructure Aerial'},
        ),
        migrations.RemoveField(
            model_name='cropsagriculture',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='infrastructureairport',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='infrastructurebridge',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='infrastructurefuel',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='infrastructureport',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='infrastructureroads',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='infrastructuretelecommunication',
            name='collect_gps_location',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='collect_gps_location',
        ),
    ]
