# Generated by Django 4.0.4 on 2022-05-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0003_alter_infrastructureairport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={'verbose_name': 'Agriculture Livestock', 'verbose_name_plural': 'Agriculture LiveStock'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='location_line',
        ),
        migrations.AlterField(
            model_name='building',
            name='number_of_storeys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_employment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_number_of_female',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_number_of_males',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_number_of_people_in_the_household',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_place_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
