# Generated by Django 4.0.4 on 2022-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0004_alter_livestock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='building',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='building',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='building',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='cropsagriculture',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='cropsagriculture',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='cropsagriculture',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='cropsagriculture',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureairport',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureairport',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureairport',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureairport',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurebridge',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurebridge',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurebridge',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurebridge',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurefuel',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurefuel',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurefuel',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructurefuel',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureport',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureport',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureport',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureport',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureroads',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureroads',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureroads',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructureroads',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructuretelecommunication',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructuretelecommunication',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructuretelecommunication',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='infrastructuretelecommunication',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilityelectricity',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilityelectricity',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilityelectricity',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilityelectricity',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilitywater',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilitywater',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilitywater',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='utilitywater',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=6544444, null=True, upload_to='photos'),
        ),
    ]
