# Generated by Django 4.0.4 on 2022-05-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0006_remove_cropsagriculture_location_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='surveyor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
