# Generated by Django 4.0.4 on 2022-05-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0007_building_surveyor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_structure',
            field=models.CharField(blank=True, choices=[('TIMBER_FRAME', 'Timber Frame'), ('WOODEN_POLE', 'Wooden Pole'), ('CONCRETE_COLUMNS', 'Concrete Columns'), ('STEEL_COLUMN', 'Steel Column'), ('LOAD_BEARING_WALL', 'Load Bearing Wall'), ('TILT_UP_SLAB', 'Tilt Up Slab'), ('UNKNOWN_OTHER', 'Unknown Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_year',
            field=models.CharField(blank=True, choices=[('NEW_(0_5_YRS)', 'New (0 5 Yrs)'), ('MEDIUM_(5_20YRS)', 'Medium (5 20Yrs)'), ('OLD_(>20YRS)', 'Old (>20Yrs)'), ('UNKNOWN', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='foundation_bracing',
            field=models.CharField(blank=True, choices=[('TIMBER_WALLS', 'Timber Walls'), ('CONCRETE_WALL', 'Concrete Wall'), ('MASONRY', 'Masonry'), ('PARTIAL_BRACING', 'Partial Bracing'), ('OTHER_(STEEL_SHEET__TIMBER_STRUTS)', 'Other (Steel Sheet  Timber Struts)'), ('NONE', 'None'), ('UNKNOWN', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='foundation_condition',
            field=models.CharField(blank=True, choices=[('5_EXCELLENT_CONDITION', '5 Excellent Condition'), ('4_GOOD_CONDITION', '4 Good Condition'), ('3_FAIR_CONDITION', '3 Fair Condition'), ('2_POOR_CONDITION', '2 Poor Condition'), ('1_VERY_POOR_CONDITION', '1 Very Poor Condition')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='foundation_type',
            field=models.CharField(blank=True, choices=[('CONCRETE_SLAB', 'Concrete Slab'), ('WOODEN_CONCRETE_PILE', 'Wooden Concrete Pile'), ('STEEL_PIPE', 'Steel Pipe'), ('WOODEN_STEEL_POLE', 'Wooden Steel Pole'), ('CONCRETE_COLUMNS', 'Concrete Columns'), ('LOAD_BEARING_WALL', 'Load Bearing Wall'), ('STEEL_COLUMN', 'Steel Column'), ('UNKNOWN', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='max_floor_height_above_ground',
            field=models.CharField(blank=True, choices=[('<1.0M_(25CM_INCREMENT)', '<1.0M (25Cm Increment)'), ('>1.0M_(50CM_INCREMENT)', '>1.0M (50Cm Increment)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='min_floor_height_above_ground',
            field=models.CharField(blank=True, choices=[('<1.0M_(25CM_INCREMENT)', '<1.0M (25Cm Increment)'), ('>1.0M_(50CM_INCREMENT)', '>1.0M (50Cm Increment)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_telecommunication_access',
            field=models.CharField(blank=True, choices=[('CELLPHONE', 'Cellphone'), ('MOBILE', 'Mobile'), ('VHF_RADIO', 'Vhf Radio'), ('INTERNET_CONNECTIVITY', 'Internet Connectivity'), ('RADIO_(AM_FM)', 'Radio (Am Fm)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='population_vehicle',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='roof_condition',
            field=models.CharField(blank=True, choices=[('5_EXCELLENT_CONDITION', '5 Excellent Condition'), ('4_GOOD_CONDITION', '4 Good Condition'), ('3_FAIR_CONDITION', '3 Fair Condition'), ('2_POOR_CONDITION', '2 Poor Condition'), ('1_VERY_POOR_CONDITION', '1 Very Poor Condition')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='roof_material',
            field=models.CharField(blank=True, choices=[('CONCRETE', 'Concrete'), ('METAL_SHEET', 'Metal Sheet'), ('FIBRE_CEMENT_SHEETS', 'Fibre Cement Sheets'), ('UNKNOWN_SHEET', 'Unknown Sheet'), ('METAL_TILES', 'Metal Tiles'), ('HEAVY_TILES', 'Heavy Tiles'), ('WOODEN_SHAKES', 'Wooden Shakes'), ('TRADITIONAL_MATERIALS', 'Traditional Materials'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='roof_pitch',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('STEEP', 'Steep')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='roof_shape',
            field=models.CharField(blank=True, choices=[('MONO_PITCH', 'Mono Pitch'), ('ARCH', 'Arch'), ('GABLE', 'Gable'), ('HIP', 'Hip'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='subuse',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('PUBLIC', 'Public'), ('EDUCATIONAL', 'Educational'), ('INSTITUTIONAL', 'Institutional'), ('STORAGE', 'Storage'), ('EVACUATION_CENTER', 'Evacuation Center'), ('NONE', 'None'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='under_storey_level',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='usage_occupancy_class',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('PUBLIC', 'Public'), ('EDUCATIONAL', 'Educational'), ('INSTITUTIONAL', 'Institutional'), ('EVACUATION_CENTER', 'Evacuation Center'), ('OUT_BUILDING', 'Out Building'), ('INFRASTRUCTURE', 'Infrastructure'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='utilities',
            field=models.CharField(blank=True, choices=[('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('TELECOMMUNICATION', 'Telecommunication'), ('ELECTRICITY_SOLAR', 'Electricity Solar'), ('WATER_TANK', 'Water Tank')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='wall_condition',
            field=models.CharField(blank=True, choices=[('5_EXCELLENT_CONDITION', '5 Excellent Condition'), ('4_GOOD_CONDITION', '4 Good Condition'), ('3_FAIR_CONDITION', '3 Fair Condition'), ('2_POOR_CONDITION', '2 Poor Condition'), ('1_VERY_POOR_CONDITION', '1 Very Poor Condition')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='wall_material',
            field=models.CharField(blank=True, choices=[('CONCRETE', 'Concrete'), ('MASONRY', 'Masonry'), ('METAL_SHEET', 'Metal Sheet'), ('FIBRE_CEMENT_SHEETS', 'Fibre Cement Sheets'), ('UNKNOWN_SHEET', 'Unknown Sheet'), ('FIBRE_CEMENT_BOARD', 'Fibre Cement Board'), ('TIMBER_BOARD', 'Timber Board'), ('UNKNOWN_BOARD', 'Unknown Board'), ('TRADITIONAL_MATERIAL', 'Traditional Material'), ('OTHER', 'Other'), ('NONE_(NO_WALLS)', 'None (No Walls)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='window_protection',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='window_type',
            field=models.CharField(blank=True, choices=[('AWNING_WINDOWS', 'Awning Windows'), ('LOUVRES', 'Louvres'), ('BAY_RECTANGLE_WINDOWS', 'Bay Rectangle Windows'), ('BOW_(OUTWARD_PROJECTED)_WINDOWS', 'Bow (Outward Projected) Windows'), ('OTHERS', 'Others')], max_length=255, null=True),
        ),
    ]
