# Generated by Django 4.0.4 on 2022-05-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revue', '0008_alter_building_building_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='population_disability',
            field=models.CharField(blank=True, choices=[('MENTAL_DISABILITY', 'Mental Disability'), ('SIGHT_DISABILITY', 'Sight Disability'), ('HEARING_DISABILITY', 'Hearing Disability'), ('WALKING_DISABILITY', 'Walking Disability')], max_length=255, null=True),
        ),
    ]
